version: '3'

services:
  mavp2p:
    build: vmc/mavp2p
    command:  serial:/dev/ttyTHS1:500000 tcps:0.0.0.0:5790 udpc:127.0.0.1:14541 --print-errors
    restart: unless-stopped
    devices:
      - "/dev/ttyTHS1:/dev/ttyTHS1"
      ports:
        - "5790:5790"
        - "14541:14541"

  mqtt:
    image: docker.io/library/eclipse-mosquitto:2.0.11
    ports:
      - "18830:18830"
    restart: unless-stopped
    volumes:
      - ./vmc/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  fcc:
    depends_on:
      - mqtt
    build: vmc/flight_control_module
    restart: unless-stopped

  pcc:
    depends_on:
      - mqtt
    build: vmc/peripheral_control_module
    restart: unless-stopped

  vio:
    depends_on:
      - mqtt
    build: vmc/vio_module
    privileged: true
    restart: unless-stopped

  apriltag:
    depends_on:
      - mqtt
    build: vmc/apriltag_module
    restart: unless-stopped
    volumes: 
      - /tmp/argus_socket:/tmp/argus_socket
    runtime: nvidia

  # sandbox:
  #   depends_on:
  #     - mqtt
  #   build: vrc_sandbox
  #   restart: unless-stopped