version: "3"

services:
  mavp2p:
    image: ghcr.io/bellflight/vrc_mavp2p:latest
    # build: vmc/mavp2p
    command: serial:/dev/ttyTHS1:500000 tcps:0.0.0.0:5790 udpc:127.0.0.1:14541 udpc:127.0.0.1:14542 --print-errors
    ports:
      - "5790:5790/tcp"
    restart: unless-stopped
    devices:
      - "/dev/ttyTHS1:/dev/ttyTHS1"

  mqtt:
    image: docker.io/library/eclipse-mosquitto:2.0.11
    ports:
      - "18830:18830"
    restart: on-failure
    volumes:
      - ./vmc/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  fcc:
    depends_on:
      - mqtt
      - mavp2p
    # build: vmc/flight_control_module
    image: ghcr.io/bellflight/vrc_flight_control_module:latest
    restart: on-failure

  pcc:
    depends_on:
      - mqtt
    # build: vmc/peripheral_control_module
    image: ghcr.io/bellflight/vrc_peripheral_control_module:latest
    restart: on-failure
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"

  vio:
    depends_on:
      - mqtt
    # build: vmc/vio_control_module
    image: ghcr.io/bellflight/vrc_vio_module:latest
    # privileged needed to connect to T265
    privileged: true
    restart: on-failure

  apriltag:
    depends_on:
      - mqtt
    build: vmc/apriltag_module
    restart: on-failure
    volumes:
      - /tmp/argus_socket:/tmp/argus_socket

  fusion:
    depends_on:
      - mqtt
      - vio
      - apriltag
    # build: vmc/fusion_module
    image: ghcr.io/bellflight/vrc_fusion_module:latest
    restart: on-failure

  # sandbox:
  #   depends_on:
  #     - mqtt
  #   build: vrc_sandbox
  #   restart: on-failure
