name: Build MAVLink/PX4

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'custom_mavlink/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Generate custom MAVLink and PX4
      run: custom_mavlink/generate.sh